Repository mapbox/android-docs, pull requests merged in 2018-08, with the labels that each got.

#558 Update contributing guidelines
  CONTRIBUTING.md
  src/example-code/boilerplate.js
Labels: update doc, ✓ ready for review

#584 re-added Turf for Java page
  batfish.config.js
  src/pages/java/overview/turf.md
Labels: mapbox-java, update doc

#588 China plugin additions
  src/pages/plugins/overview/index.md
Labels: update doc, ✓ ready for review

#601 Updates for Navigation SDK 0.17.0
  src/pages/navigation/overview/navigation-options.md
  src/pages/navigation/overview/navigation-ui.md
Labels: navigation-sdk, ✓ ready for review

#602 Added mention of China token requirement
  src/pages/plugins/overview/china.md
Labels: maps-sdk, update doc, ✓ ready for review

#608 Location layer plugin 0.7.2 bump + api docs
  api/plugins/locationlayer/0.7.2/allclasses-frame.html
  api/plugins/locationlayer/0.7.2/allclasses-noframe.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/CompassListener.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerOptions.Builder.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerOptions.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/OnCameraTrackingChangedListener.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/OnLocationLayerClickListener.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/OnLocationLayerLongClickListener.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/OnLocationStaleListener.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/Utils.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/modes/CameraMode.Mode.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/modes/CameraMode.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/modes/RenderMode.Mode.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/modes/RenderMode.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/modes/package-frame.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/modes/package-summary.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/modes/package-tree.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/package-frame.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/package-summary.html
  api/plugins/locationlayer/0.7.2/com/mapbox/mapboxsdk/plugins/locationlayer/package-tree.html
  api/plugins/locationlayer/0.7.2/constant-values.html
  api/plugins/locationlayer/0.7.2/deprecated-list.html
  api/plugins/locationlayer/0.7.2/help-doc.html
  api/plugins/locationlayer/0.7.2/index-all.html
  api/plugins/locationlayer/0.7.2/index.html
  api/plugins/locationlayer/0.7.2/overview-frame.html
  api/plugins/locationlayer/0.7.2/overview-summary.html
  api/plugins/locationlayer/0.7.2/overview-tree.html
  api/plugins/locationlayer/0.7.2/package-list
  api/plugins/locationlayer/0.7.2/script.js
  api/plugins/locationlayer/0.7.2/stylesheet.css
  src/constants.js
Labels: work in progress
