Repository mapbox/android-docs, pull requests merged in 2019-02, with the labels that each got.

#844 Added blurb and code snippets about removing sources/layers
  src/pages/maps/overview/annotations.md
  src/pages/maps/overview/data-driven-styling.md
Labels: maps-sdk

#847 Annotation and dds tweaks based on Colleen review
  src/pages/maps/overview/annotations.md
  src/pages/maps/overview/data-driven-styling.md
Labels: ✓ ready for review

#845 Adding writing and coding snippet about location listening weakreference setup
  src/pages/core/overview/index.md
Labels: ⚠️ DO NOT MERGE, ✓ ready for review

#863 Fix last location retrieval from LocationResult in core docs
  src/pages/core/overview/index.md
Labels: ✓ ready for review
